services:
  json-rpc-proxy:
    build: .
    ports:
      - '127.0.0.1:8000:8000'
    environment:
      HOST: "localhost"
      PORT: "80"
      ALLOWED_METHODS: "*"
      AUTHORIZATION_HEADER_OVERRIDE: "" # Optional, set to override the Authorization header, e.g., "Basic B64string="
    restart: always
